name: Upload to PyPi

on:
  workflow_call:
    secrets:
      TWINE_PASS:
        required: true

jobs:
  upload-to-pypi:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Sets up python
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Install dependencies
      - name: "Installs dependencies"
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools build wheel twine

      # Build and upload to PyPI
      - name: "Builds and uploads to PyPI"
        run: |
          python -m build
          python -m twine upload dist/*

        env:
          TWINE_USERNAME: martvanrijthoven
          TWINE_PASSWORD: ${{ secrets.TWINE_PASS }}