name: Create GitHub Release

on:
  workflow_call:

jobs:
  create-github-release:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: release version
        run: |
          python -m pip install .
          python .github/scripts/release.py
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}